# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: rgosocks5

before:
  hooks:
    - go mod tidy
    - go test ./... -v

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X rgosocks/version.version={{ .Version }}
      - -X rgosocks/version.commit={{ .Commit }}
      - -X rgosocks/version.date={{ .Date }}
    goos:
      - windows
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    goamd64:
      - v1
      - v3

dockers_v2:
  - images:
      - raerten/rgosocks5
    tags:
      - "{{ .Tag }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
    labels:
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
    extra_files:
      - .build/passwd

archives:
  - #
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64_
      {{- else if eq .Arch "386" }}i386_
      {{- else }}{{ .Arch }}_{{ end }}
      {{- if .Arm }}v{{ .Arm }}_{{ end }}
      {{- if .Amd64 }}{{ .Amd64 }}_{{ end }}
      {{- .Summary }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
    builds_info:
      mode: 0777

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
