# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

project_name: rgosocks5

before:
  hooks:
    - go mod tidy
    - go test ./... -v

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    goamd64:
      - v1
      - v3

dockers:
  - image_templates:
      - raerten/rgosocks5:latest-amd64
      - raerten/rgosocks5:{{ .Tag }}-amd64
    goos: linux
    goarch: amd64
    goamd64: v1
    skip_push: false
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
    extra_files:
      - .build/passwd
  - image_templates:
      - raerten/rgosocks5:latest-arm64v8
      - raerten/rgosocks5:{{ .Tag }}-arm64v8
    goos: linux
    goarch: arm64
    skip_push: false
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
    extra_files:
      - .build/passwd
  - image_templates:
      - raerten/rgosocks5:latest-armv7
      - raerten/rgosocks5:{{ .Tag }}-armv7
    goos: linux
    goarch: arm
    goarm: "7"
    skip_push: false
    build_flag_templates:
      - --platform=linux/arm/v7
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
    extra_files:
      - .build/passwd

docker_manifests:
  - name_template: raerten/rgosocks5:{{ .Tag }}
    image_templates:
      - raerten/rgosocks5:{{ .Tag }}-amd64
      - raerten/rgosocks5:{{ .Tag }}-arm64v8
      - raerten/rgosocks5:{{ .Tag }}-armv7
  - name_template: raerten/rgosocks5:latest
    image_templates:
      - raerten/rgosocks5:latest-amd64
      - raerten/rgosocks5:latest-arm64v8
      - raerten/rgosocks5:latest-armv7

archives:
  - #
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64_
      {{- else if eq .Arch "386" }}i386_
      {{- else }}{{ .Arch }}_{{ end }}
      {{- if .Arm }}v{{ .Arm }}_{{ end }}
      {{- if .Amd64 }}{{ .Amd64 }}_{{ end }}
      {{- .Summary }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      mode: 0777

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
